### ISSUE TITLE
Windows Configuration File is not working

### ISSUE THREAD

**Issue by SheikhTalal** [angristan/wireguard-install#121]
Dear Author,

Thanks for the lovely effort in building this code. I installed the script on Ubuntu 20.04.1 LTS and on Debian Buster 10.5 and both are working flawlessly but when I copy the configuration file to my laptop (Windows 10 Pro) to connect to both server it makes handshake for 1 time only and then the connection is lost... Any Idea about the issue?

Thanks in advance

**Comment by drphr4ud** [comment]
Two days ago I did an install and exported the client config to a txt file, then imported on Windows 10, 1909 and Windows 10, 2004 machines running Wireguard 64 bit https://download.wireguard.com/windows-client/wireguard-amd64-0.1.1.msi

No issues. Continuous connectivity. Comes right back on reboot, too. @SheikhTalal please submit more details. 

Are you making new profiles for each client ? 1 client profile can only be used for one session because the internal ip addresses are tied to the peer.

**Comment by SheikhTalal** [comment]
Thanks a lot for your reply, I was putting the DNS server the internal IP: 10.66.66.1 but I had a bad configuration to the local DNS.

Once I fixed, it worked flawlesly and it can work if I put any public DNS in the configuration ....
