### ISSUE TITLE
Error on Line#111

### ISSUE THREAD

**Issue by Haris-K** [angristan/wireguard-install#56]
Getting these error when running script after IPV4 detection. Please help me out. I already shared where i am facing trouble.

Want to use a pre-shared symmetric key? [Y/n]: y
IPv4 Detected
./wireguard-install.sh: line 111: wg: command not found
./wireguard-install.sh: line 112: wg: command not found
./wireguard-install.sh: line 115: wg: command not found
./wireguard-install.sh: line 116: wg: command not found
./wireguard-install.sh: line 146: wg: command not found
* Applying /etc/sysctl.d/98-rpi.conf ...
kernel.printk = 3 4 1 3
vm.min_free_kbytes = 16384
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /etc/sysctl.d/protect-links.conf ...
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.d/wg.conf ...
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
* Applying /etc/sysctl.conf ...
Failed to start wg-quick@wg0.service: Unit wg-quick@wg0.service not found.
Failed to enable unit: Unit file wg-quick@wg0.service does not exist.

Thank you

**Comment by angristan** [comment]
Please share the whole output. Looks like Wireguard has not been installed.

**Comment by randomshell** [comment]
The problem seems to be that on Raspbian `$OS` is `raspbian` and the script doesn't have a case for this and nothing gets installed.

@angristan in the openvpn repo `$OS` is set to `debian` and the `$ID` is used for `raspbian` or `debian`.

Same as https://github.com/angristan/wireguard-install/issues/17#issuecomment-520180642
