### ISSUE TITLE
error:Job for wg-quick@wg0.service failed because the control process exited with error code. See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

### ISSUE THREAD

**Issue by zxyboy** [angristan/wireguard-install#78]
i have been executed follow command 

```
 curl -O https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh
chmod +x wireguard-install.sh
./wireguard-install.sh
```
but the error happen
```
Job for wg-quick@wg0.service failed because the control process exited with error code. See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

Here is your client config file as a QR Code:

```
my OS is centos7, kenel version is 
`4.10.4-1.el7.elrepo.x86_64 `

i do not know why it happen ?

**Comment by handsomego** [comment]
I also met the error, but I rm -rf /etc/wireguard , it can work for me Ubuntu 20.04

**Comment by randomshell** [comment]
Did you see `systemctl status wg-quick@wg0.service` and `journalctl -xe` for details? Can you paste here the relevant lines?

**Comment by angristan** [comment]
We need the output of `systemctl status wg-quick@wg0.service` to know what isn't working.

**Comment by chrmat** [comment]
I have the same issue in ubuntu 18.04.4
systemctl status wg-quick@wg0.service
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-06-22 21:58:11 CEST; 1min 9s ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
  Process: 31375 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=1/FAILURE)
 Main PID: 31375 (code=exited, status=1/FAILURE)

juni 22 21:58:11 htpc systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
juni 22 21:58:11 htpc wg-quick[31375]: [#] ip link add wg0 type wireguard
juni 22 21:58:11 htpc wg-quick[31375]: RTNETLINK answers: Operation not supported
juni 22 21:58:11 htpc wg-quick[31375]: Unable to access interface: Protocol not supported
juni 22 21:58:11 htpc wg-quick[31375]: [#] ip link delete dev wg0
juni 22 21:58:11 htpc wg-quick[31375]: Cannot find device "wg0"
juni 22 21:58:11 htpc systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE
juni 22 21:58:11 htpc systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
juni 22 21:58:11 htpc systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.

**Comment by chrmat** [comment]
Reinstalled wireguard packages, and it is working again. It seems like the problem was due to a linux kernel update after the original install.
